# Generated by Django 4.1.3 on 2022-11-19 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productdesigngroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=254, null=True)),
                ('product_design_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_design_group_for_category', to='products.productdesigngroup')),
            ],
            options={
                'verbose_name_plural': 'Design Categories',
            },
        ),
    ]
