# Generated by Django 4.1.3 on 2022-11-19 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_design_product_design_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='product_design_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_design_group', to='products.productdesigngroup'),
        ),
    ]
