# Generated by Django 4.1.3 on 2022-11-19 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_design_product_design_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='product_design_group',
        ),
    ]
