# Generated by Django 4.1.3 on 2022-11-19 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_color_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_link', models.URLField(blank=True, db_index=True, max_length=256, unique=True)),
                ('name', models.CharField(max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField()),
                ('main_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.design')),
            ],
        ),
    ]
