# Generated by Django 4.1.3 on 2022-11-19 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productoptions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoptions',
            options={'verbose_name_plural': 'Product Options'},
        ),
        migrations.AddField(
            model_name='productoptions',
            name='article_nr',
            field=models.CharField(default=0, max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(15)]),
            preserve_default=False,
        ),
    ]
