# Generated by Django 4.1.3 on 2022-11-23 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='main_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='productimages',
            old_name='main_image_url',
            new_name='image_url',
        ),
    ]
